### ISSUE TITLE
只预览一张图片，隐藏了toolbar，和navbar，点击cell，退出VC该怎么实现

### ISSUE THREAD

**Issue by xiky** [banchichen/TZImagePreviewController#13]
如题，继承这个控制器，在viewDidLoad 或者 touchBegin 方法里调用返回，但是事件并没有传递到继承的控制器里，didTapPreviewCell 这个方法也没有暴露出来，我要实现的话，只能修改源码吗？

**Comment by banchichen** [comment]
嗯，源码搬过去吧，也就2个文件
