### ISSUE TITLE
请问如何显示当前图片对应的 index？

### ISSUE THREAD

**Issue by rakuyoMo** [banchichen/TZImagePreviewController#14]
我看好像有一个 `indexLabel`，但是在 setPhotoPreviewPageDidLayoutSubviewsBlock 里设置其为 `indexLabel.hidden = NO;` 没有效果...

**Comment by banchichen** [comment]
把这几行干掉，就会显示了：
![image](https://user-images.githubusercontent.com/12755494/74350439-b2793880-4df0-11ea-9e6c-3f537f366763.png)

**Comment by rakuyoMo** [comment]
这几行干掉之后显示的是总数，我希望显示，当前图片是 1，滑到下一张是 2，就是显示这张图片对应的 index... 请问有办法吗

**Comment by banchichen** [comment]
你玩玩demo哈，注释这几行后，右上角显示的是当前序号的

底部的完成按钮那显示的才是总数，不过这里不支持显示当前序号...

**Comment by banchichen** [comment]
实在要改的话，可以去改库里的代码，这个库只有2个文件

**Comment by rakuyoMo** [comment]
可以了！原来是我漏掉了 `showSelectedIndex` 这个属性....
