### ISSUE TITLE
'TZImagePickerController/UIView+Layout.h' file not found

### ISSUE THREAD

**Issue by sec7et** [banchichen/TZImagePreviewController#19]
配合着 TZImagePickerController 一起使用，在 TZImagePreviewController.m 文件中会提示：'TZImagePickerController/UIView+Layout.h' file not found。

实际上 UIView+Layout.h 文件已经改名为 UIView+TZLayout.h ，修改为：
`#import <TZImagePickerController/UIView+TZLayout.h>`
就正常了，希望能尽快更新一下，谢谢。

**Comment by sec7et** [comment]
- TZImagePickerController (3.5.7)
  - TZImagePreviewController (0.4.0):

**Comment by banchichen** [comment]
新版本0.5.0哈
