### ISSUE TITLE
隐藏 `_toolBar` 显示页面，再次点击页面，`_toolBar` 会重新显示

### ISSUE THREAD

**Issue by rakuyoMo** [banchichen/TZImagePreviewController#22]
https://github.com/banchichen/TZImagePreviewController/blob/04813f8f1c2127013a71e0f19c5a76e30d0bc106/TZImagePreviewController/TZImagePreviewController/TZImagePreviewController.m#L312-L316

这个方法里直接对 `hidden` 取反，没有考虑到在 `photoPreviewPageUIConfigBlock` 里对 `_toolBar` 隐藏了的情况。

**Comment by banchichen** [comment]
建议可以hook下didTapPreviewCell，替换为空的实现

或者要加一个属性，提个PR，在点击cell的时候，不取反isHideNaviBar

**Comment by rakuyoMo** [comment]
> 建议可以hook下didTapPreviewCell，替换为空的实现
> 
> 或者要加一个属性，提个PR，在点击cell的时候，不取反isHideNaviBar

我们提了一个 pr，麻烦看一下能否合并：#23
