### ISSUE TITLE
支持再次选择图片时,之前选择的图片选中状态吗?

### ISSUE THREAD

**Issue by dboce** [banchichen/TZImagePreviewController#5]
再次选择时,之前选中了几张图片有记录吗

**Comment by dboce** [comment]
还有您Demo中_selectedPhotos中获取到的图片数组是PHAsset格式图片,有返回UIImage图片数组的方法吗?

**Comment by banchichen** [comment]
这个只能预览，如果要选择，去看 https://github.com/banchichen/TZImagePickerController ，Demo默认效果就会记录上次选中。

不行，_selectedPhotos里的对象是什么类型，返回的就是什么类型...
