### ISSUE TITLE
预览时如何隐藏左上角勾选按钮和完成按钮？

### ISSUE THREAD

**Issue by lczalh** [banchichen/TZImagePreviewController#8]
预览时如何隐藏左上角勾选按钮和完成按钮？

**Comment by banchichen** [comment]
TZImagePickerController的photoPreviewPageUIConfigBlock、photoPreviewPageDidLayoutSubviewsBlock两个设置项也能生效的，尝试设置下

**Comment by lczalh** [comment]
我这样写 回调没走
let  pickerController = TZImagePickerController(maxImagesCount: 999, columnNumber: 4, delegate: nil)
            pickerController!.photoPickerPageUIConfigBlock = { collectionView, bottomToolBar, previewButton, originalPhotoButton, originalPhotoLabel, doneButton, numberImageView, numberLabel, divideLine in
                doneButton?.isHidden = true
            }
            pickerController!.photoPickerPageDidLayoutSubviewsBlock = { collectionView,bottomToolBar, previewButton, originalPhotoButton, originalPhotoLabel, doneButton, numberImageView, numberLabel, divideLine in
                numberLabel?.isHidden = true
            }

**Comment by banchichen** [comment]
你写错了，不是photoPickerPageUIConfigBlock，是photoPreviewPageUIConfigBlock

**Comment by lczalh** [comment]
走进来了 可以修改文字，但是设置isHidden还是无法隐藏。 
imagePickerController.photoPreviewPageUIConfigBlock = { collectionView, naviBar, backButton, selectButton, indexLabel, toolBar, originalPhotoButton, originalPhotoLabel, doneButton, numberImageView, numberLabel in
            DispatchQueue.main.async {
                doneButton?.isHidden = true
            }
        }
按钮也不能替换 提示它是let。我只能removeFromSuperview()

**Comment by banchichen** [comment]
你应该设置hidden=true....
